### ISSUE TITLE
sthttpd does not compile with gcc-15.1.1

### ISSUE THREAD

**Issue by kirxkirx** [blueness/sthttpd#19]
````
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT thttpd.o -MD -MP -MF .deps/thttpd.Tpo -c -o thttpd.o thttpd.c
thttpd.c: In function 'main':
thttpd.c:610:12: error: implicit declaration of function 'sigset'; did you mean 'isset'? [-Wimplicit-function-declaration]
  610 |     (void) sigset( SIGTERM, handle_term );
      |            ^~~~~~
      |            isset
thttpd.c: In function 'thttpd_logstats':
thttpd.c:2182:75: warning: format '%lld' expects argument of type 'long long int', but argument 6 has type 'long int' [-Wformat=]
 2182 |             "  thttpd - %ld connections (%g/sec), %d max simultaneous, %lld bytes (%g/sec), %d httpd_conns allocated",
      |                                                                        ~~~^
      |                                                                           |
      |                                                                           long long int
      |                                                                        %ld
 2183 |             stats_connections, (float) stats_connections / secs,
 2184 |             stats_simultaneous, (int64_t) stats_bytes,
      |                                 ~~~~~~~~~~~~~~~~~~~~~                      
      |                                 |
      |                                 long int
thttpd.c: In function 'main':
thttpd.c:486:12: warning: ignoring return value of 'getcwd' declared with attribute 'warn_unused_result' [-Wunused-result]
  486 |     (void) getcwd( cwd, sizeof(cwd) - 1 );
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
thttpd.c: In function 'handle_alrm':
thttpd.c:307:16: warning: ignoring return value of 'chdir' declared with attribute 'warn_unused_result' [-Wunused-result]
  307 |         (void) chdir( "/tmp" );
      |                ^~~~~~~~~~~~~~~
make[2]: *** [Makefile:403: thttpd.o] Error 1
````

The compilation works fine if I...
````
# Add the compatibility define
sed -i 's/#include <signal.h>/#define _GNU_SOURCE\n#include <signal.h>/' src/thttpd.c

# Compile with compatibility flags  
make CFLAGS="-g -O2 -Wno-implicit-function-declaration -D_GNU_SOURCE"
`````
